In [4]:
!pip3 install imageio

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     |████████████████████████████████| 313 kB 379 kB/s eta 0:00:01


In [5]:
import imageio

In [6]:
im = imageio.imread("1.jpg")

/var/folders/nq/h14f6pfn34l442ftf2dd6g780000gn/T/ipykernel_5716/2702584100.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im = imageio.imread("1.jpg")


In [77]:
help(im.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [79]:
im.shape, im.mean(0), im.mean(1), im.mean(2)#, im.mean(3)

((2316, 3088, 3),
 array([[163.09455959, 157.25993092, 152.62823834],
        [163.65889465, 157.82469775, 153.19084629],
        [163.62348877, 157.7888601 , 153.15544041],
        ...,
        [ 37.35794473,  39.92141623,  42.83462867],
        [ 37.17055268,  39.6148532 ,  42.66018998],
        [ 37.04317789,  39.50690846,  42.53756477]]),
 array([[117.81703368, 117.74838083, 117.80667098],
        [118.36690415, 118.2878886 , 118.34423575],
        [118.19689119, 118.08646373, 118.1865285 ],
        ...,
        [158.25032383, 142.59488342, 128.15576425],
        [158.32091969, 142.60621762, 128.05408031],
        [158.19073834, 142.4488342 , 127.83387306]]),
 array([[148.33333333, 144.33333333, 142.33333333, ...,  32.33333333,
          32.33333333,  33.33333333],
        [149.33333333, 145.33333333, 143.33333333, ...,  35.33333333,
          36.33333333,  27.33333333],
        [149.33333333, 145.33333333, 144.33333333, ...,  31.33333333,
          33.33333333,  28.33333333],
    

In [13]:
#help(imageio.imread)
#help(im)

import torch

tensor_im = torch.from_numpy(im)

In [18]:
out = tensor_im.permute(2, 0, 1)
out = out.float()

torch.mean(out), torch.std(out)

(tensor(123.1673), tensor(63.3897))

In [19]:
import numpy as np 

In [30]:
csv = np.loadtxt("order.csv",delimiter=',', skiprows=1)

In [32]:
csv.shape, csv

((5, 4),
 array([[2.14602184e+09, 1.51733686e+09, 0.00000000e+00, 0.00000000e+00],
        [2.14602184e+09, 1.51733754e+09, 0.00000000e+00, 0.00000000e+00],
        [2.14602184e+09, 1.51735479e+09, 5.27400000e+03, 5.27400000e+03],
        [2.14602184e+09, 1.51739219e+09, 0.00000000e+00, 0.00000000e+00],
        [2.14602184e+09, 1.51739449e+09, 0.00000000e+00, 0.00000000e+00]]))

In [58]:
target = torch.from_numpy(csv)
target

tensor([[2.1460e+09, 1.5173e+09, 0.0000e+00, 0.0000e+00],
        [2.1460e+09, 1.5173e+09, 0.0000e+00, 0.0000e+00],
        [2.1460e+09, 1.5174e+09, 5.2740e+03, 5.2740e+03],
        [2.1460e+09, 1.5174e+09, 0.0000e+00, 0.0000e+00],
        [2.1460e+09, 1.5174e+09, 0.0000e+00, 0.0000e+00]], dtype=torch.float64)

In [98]:
target_onehot = torch.zeros(target.shape[0], 2, dtype=float)
target_onehot, target_onehot.dtype, target_onehot.shape

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 torch.float64,
 torch.Size([5, 2]))

In [99]:
target_onehot.scatter_(1, torch.tensor([[1], [0], [1], [1], [1]]), target)

tensor([[0.0000e+00, 2.1460e+09],
        [2.1460e+09, 0.0000e+00],
        [0.0000e+00, 2.1460e+09],
        [0.0000e+00, 2.1460e+09],
        [0.0000e+00, 2.1460e+09]], dtype=torch.float64)

In [71]:
target_onehot.scatter_(1, torch.tensor([[0], [1], [1], [1], [1]]), target)

tensor([[2.1460e+09, 0.0000e+00],
        [0.0000e+00, 2.1460e+09],
        [0.0000e+00, 2.1460e+09],
        [0.0000e+00, 2.1460e+09],
        [0.0000e+00, 2.1460e+09]], dtype=torch.float64)

In [89]:
import torch

# Create a tensor to scatter values into
tensor = torch.zeros(3, 3,dtype=float)

# Define indices where you want to scatter values
indices = torch.tensor([[0, 1, 2],
                        [1, 0, 2]])

# Define source values to scatter
values = torch.tensor([[1, 1, 1],
                       [2, 2, 2]],dtype=float)

# Scatter the values into the tensor along the specified dimension (dim=0 in this case)
result = tensor.scatter(dim=0, index=indices, src=values)

print(result)


tensor([[1., 2., 0.],
        [2., 1., 0.],
        [0., 0., 2.]], dtype=torch.float64)


In [75]:
help(target.stride)

Help on built-in function stride:

stride(...) method of torch.Tensor instance
    stride(dim) -> tuple or int
    
    Returns the stride of :attr:`self` tensor.
    
    Stride is the jump necessary to go from one element to the next one in the
    specified dimension :attr:`dim`. A tuple of all strides is returned when no
    argument is passed in. Otherwise, an integer value is returned as the stride in
    the particular dimension :attr:`dim`.
    
    Args:
        dim (int, optional): the desired dimension in which stride is required
    
    Example::
    
        >>> x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
        >>> x.stride()
        (5, 1)
        >>> x.stride(0)
        5
        >>> x.stride(-1)
        1



In [82]:
!pip3 install torchvision

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     |████████████████████████████████| 1.7 MB 101 kB/s eta 0:00:01


In [84]:
## rgb mean
# Python program to find mean across the image channels
# import necessary libraries
import torch
from PIL import Image
import torchvision.transforms as transforms

# Read the input image
img = Image.open('1.jpg')

# Define transform to convert the image to PyTorch Tensor
transform = transforms.ToTensor()

# Convert image to PyTorch Tensor (Image Tensor)
imgTensor = transform(img)
print("Shape of Image Tensor:\n", imgTensor.shape)

# Compute mean of the Image Tensor across image channels RGB
R_mean, G_mean ,B_mean = torch.mean(imgTensor, dim = [1,2])

# print mean across image channel RGB
print("Mean across Red channel:", R_mean)
print("Mean across Green channel:", G_mean)
print("Mean across Blue channel:", B_mean)

imgTensor[0,:6,:6]

Shape of Image Tensor:
 torch.Size([3, 2316, 3088])
Mean across Red channel: tensor(0.5085)
Mean across Green channel: tensor(0.4794)
Mean across Blue channel: tensor(0.4611)


tensor([[0.5961, 0.5804, 0.5725, 0.5804, 0.5843, 0.5765],
        [0.6000, 0.5843, 0.5765, 0.5843, 0.5922, 0.5843],
        [0.6000, 0.5843, 0.5804, 0.5961, 0.6000, 0.5882],
        [0.6039, 0.5882, 0.5882, 0.6000, 0.6000, 0.5882],
        [0.5961, 0.5922, 0.5922, 0.5961, 0.5922, 0.5882],
        [0.5882, 0.5961, 0.6000, 0.5922, 0.5843, 0.5882]])

In [105]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]],dtype=float)

tensor.mean(dim=1)

tensor([2., 5.], dtype=torch.float64)